apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: diplomska
type: Opaque
data:
  username: LW4gJ3dhdGVyX3Bvc3RncmVzX3VzZXInIA0K
  password: LW4gJ3Zzb2lqOTNDS1dKRUxLQ0owOWMwajkyajkwYzIzZCcgDQo=
  key_password: LW4gJzlmODJoamtjamgyOTgzaGQyOXVuZHg5MDhvMkQ4SEozOTA4RkRIJyANCg==
  key_location: LW4gJy9ldGMvc3NsL3ByaXZhdGUvc3ByaW5nYm9vdC5wMTInIA0K